services:
  - type: web
    name: hostel-search-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      echo "Current directory: $(pwd)"
      echo "Listing contents of current directory:"
      ls -la
      echo "Creating data directory..."
      mkdir -p /opt/render/project/src/data
      echo "Copying files..."
      cp -v hostel_index.faiss hostel_ids.npy /opt/render/project/src/data/
      echo "Verifying files in data directory:"
      ls -la /opt/render/project/src/data/
    startCommand: gunicorn app:app
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: FLASK_ENV
        value: production
    disk:
      name: data
      mountPath: /data
      sizeGB: 1 